services:
  - type: web
    name: nuoi-mot-thu
    runtime: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO
        value: dobietdc/bot-artwork
      - key: HF_ARTWORK_URL
        value: https://huggingface.co/datasets/dobietdc/bot-artwork/resolve/main
      - key: ADMIN_PASSWORD
        sync: false
